# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# Docker-in-Docker
image:
  name: docker/compose:1.24.1
  entrypoint: ["sh", "-c"]

services:
  # https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
  - name: docker:20.10.7-dind
    alias: docker

variables:
  VARIANT: alpine
  DOCKER_REPO: monogramm/ldap-one-for-all
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  # This instructs Docker NOT to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # This instructs Docker to start over TLS.
  #DOCKER_TLS_CERTDIR: "/certs"

# Check docker
before_script:
  - pwd
  - id
  - apk add bash git
  - docker --version
  - docker-compose --version
  - docker info

# Always cleanup after the build
after_script:
  - docker images
  - docker image prune -f --filter until=$(TZ=EST+24 date +%Y-%m-%d)

# Execute CI build hooks
build-hooks:
  stage: build
  tags:
    - docker
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  script:
    # Export variables to tag against GitLab Registry
    #- [ -z "${CI_REGISTRY_IMAGE}" ] || export DOCKER_REPO=${$CI_REGISTRY_IMAGE}
    - export STORIES=true
    - export EXPORT_TESTS_RESULTS=true
    - ./hooks/run build "${VARIANT}"
    # Save docker image as artifact
    - mkdir -p .docker/image
    - docker save "${DOCKER_REPO}:${VARIANT}" > .docker/image/app.tar
  artifacts:
    expire_in: 24 hrs
    paths:
      - .docker/image

# Execute CI test hooks
test-hooks:
  stage: test
  tags:
    - docker
  script:
    # Load artifact from build stage
    - docker load -i .docker/image/app.tar
    - ./hooks/run test "${VARIANT}"

# Publish images
#push-hooks:
#  stage: deploy
#  tags:
#    - docker
#  script:
#    # Export variables to login and push to GitLab Registry
#    - [ -z "${CI_REGISTRY_IMAGE}" ] || export DOCKER_LOGIN=${CI_REGISTRY_USER}
#    - [ -z "${CI_REGISTRY_IMAGE}" ] || export DOCKER_PASSWORD=${CI_REGISTRY_PASSWORD}
#    - [ -z "${CI_REGISTRY_IMAGE}" ] || export DOCKER_REGISTRY=${CI_REGISTRY}
#    # Load artifact from build stage
#    - docker load -i .docker/image/app.tar
#    - ./hooks/run push

# Publish test results
#push-coverage:
#  stage: deploy
#  script:
#    - echo "TBD"

# Deploy to stage
#staging:
#  stage: staging
#  script:
#    - echo "TBD"

# Deploy to production
#production:
#  stage: production
#  script:
#    - echo "TBD"
#  when: manual
#  only:
#    - master
