#!/bin/sh
set -e

###########################################################
# Functions

TODAY=$(date +%Y-%m-%d)

log() {
    MESSAGE="[$0] [$(date +%Y-%m-%dT%H:%M:%S)] ${1}"

    echo "${MESSAGE}"
    echo "${MESSAGE}" >> "/var/log/cron_${TODAY}.log"
}

sf_console() {
    php /var/www/html/bin/console "$@" >> "/var/log/cron_${TODAY}.log"
}

###########################################################
# Runtime

log "Deleting expired password reset codes from the database..."

sf_console 'app:password-reset-codes:delete-expired'

log "Delete of expired password reset codes from the database successful"
