app_metrics:
    #resource: '@ArtprimaPrometheusMetricsBundle/Resources/config/routing.xml'
    path: /api/metrics/prometheus
    controller: Artprima\PrometheusMetricsBundle\Controller\MetricsController::prometheus
